// ----------------------------------------------
package com.cisco.ccbu.cce.unifiedconfig.toolkit.bean;

import com.cisco.ccbu.cce.unifiedconfig.toolkit.BaseApiBean;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.ws.rs.Path;
import javax.xml.bind.annotation.XmlRootElement;
import java.util.List;
import com.cisco.ccbu.cce.unifiedconfig.toolkit.ReferenceBean;
import java.util.Date;
import com.cisco.ccbu.cce.unifiedconfig.toolkit.BaseApiListBean;

import javax.xml.bind.annotation.XmlElement;

import javax.xml.bind.annotation.XmlElementWrapper;


@Path("machineinventory")
@XmlRootElement(name="machine")
public class MachineHost extends BaseApiBean {
  private List<MachineAddress> addresses;
  private Boolean autoGenerated;
  private Integer changeStamp;
  private String correlationId;
  private ReferenceBean department;
  private String description;
  private String hostName;
  private MachineType machineType;
  private MachineVersion machineVersion;
  private String name;
  private String refURL;
  private ReferenceBean vmHostRef;
  private String vmInstanceUuid;

  @XmlElementWrapper(name="networks")
  @XmlElement(name="network")
  public List<MachineAddress> getAddresses() {
     return this.addresses;
  }

  public void setAddresses(List<MachineAddress> addresses) {
     this.addresses = addresses;
  }

  public Boolean getAutoGenerated() {
     return this.autoGenerated;
  }

  public void setAutoGenerated(Boolean autoGenerated) {
     this.autoGenerated = autoGenerated;
  }

  public Integer getChangeStamp() {
     return this.changeStamp;
  }

  public void setChangeStamp(Integer changeStamp) {
     this.changeStamp = changeStamp;
  }

  public String getCorrelationId() {
     return this.correlationId;
  }

  public void setCorrelationId(String correlationId) {
     this.correlationId = correlationId;
  }

  public ReferenceBean getDepartment() {
     return this.department;
  }

  public void setDepartment(ReferenceBean department) {
     this.department = department;
  }

  public String getDescription() {
     return this.description;
  }

  public void setDescription(String description) {
     this.description = description;
  }

  public String getHostName() {
     return this.hostName;
  }

  public void setHostName(String hostName) {
     this.hostName = hostName;
  }

  @XmlElement(name="type")
  public MachineType getMachineType() {
     return this.machineType;
  }

  public void setMachineType(MachineType machineType) {
     this.machineType = machineType;
  }

  @XmlElement(name="versionInfo")
  public MachineVersion getMachineVersion() {
     return this.machineVersion;
  }

  public void setMachineVersion(MachineVersion machineVersion) {
     this.machineVersion = machineVersion;
  }

  public String getName() {
     return this.name;
  }

  public void setName(String name) {
     this.name = name;
  }

  public String getRefURL() {
     return this.refURL;
  }

  public void setRefURL(String refURL) {
     this.refURL = refURL;
  }

  @XmlElement(name="vmHost")
  public ReferenceBean getVmHostRef() {
     return this.vmHostRef;
  }

  public void setVmHostRef(ReferenceBean vmHostRef) {
     this.vmHostRef = vmHostRef;
  }

  public String getVmInstanceUuid() {
     return this.vmInstanceUuid;
  }

  public void setVmInstanceUuid(String vmInstanceUuid) {
     this.vmInstanceUuid = vmInstanceUuid;
  }


  @Path("machineinventory")
  @XmlRootElement(name = "results")
  public static class MachineHostList extends BaseApiListBean<MachineHost> {
    @XmlElementWrapper(name = "machines")
    @XmlElement(name = "machine")
    public List<MachineHost> getItems() {
      return items;
    }

    public void setItems(List<MachineHost> items) {
      this.items = items;
    }
  }
}
